create table public.transport_messages (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.transport_requests(id) on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  message text not null check (char_length(btrim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index transport_messages_request_created_idx
  on public.transport_messages (request_id, created_at, id);

alter table public.transport_messages enable row level security;

grant select, insert on public.transport_messages to authenticated;
grant usage, select on sequence public.transport_messages_id_seq to authenticated;

create policy "Workspace members can read request messages"
on public.transport_messages
for select
to authenticated
using (
  sender_id = (select auth.uid())
  or exists (
    select 1
    from public.transport_requests r
    join public.workspace_members m on m.workspace_id = r.workspace_id
    where r.id = transport_messages.request_id
      and r.workspace_id = transport_messages.workspace_id
      and m.user_id = (select auth.uid())
  )
);

create policy "Workspace members can send request messages"
on public.transport_messages
for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and exists (
    select 1
    from public.transport_requests r
    join public.workspace_members m on m.workspace_id = r.workspace_id
    where r.id = transport_messages.request_id
      and r.workspace_id = transport_messages.workspace_id
      and m.user_id = (select auth.uid())
  )
);

alter publication supabase_realtime add table public.transport_messages;
notify pgrst, 'reload schema';
